# Generated by Django 4.2 on 2025-11-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('logo_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='herosection',
            name='profile_image',
            field=models.ImageField(upload_to='media/hero_images/'),
        ),
    ]
